# Site settings
title: WSO2 Visual Elements
name: wso2-visual-elements
version: 1.0.0
url: wso2-dev-ux.github.io/theme-wso2/
license: https://github.com/wso2-dev-ux/theme-wso2/blob/master/LICENSE
baseurl: ""