# Site settings
title: Theme WSO2
name: theme-wso2
version: 1.0.0
url: wso2-dev-ux.github.io/theme-wso2/
license: https://github.com/wso2-dev-ux/theme-wso2/blob/master/LICENSE
baseurl: "/"
permalink: /:title/
sass:
  sass_dir: _scss